### ISSUE TITLE
Overlapping macro layouts

### ISSUE THREAD

**Issue by mbaykenar** [lnis-uofu/SOFA#145]
Hi,

When I analyze gds outputs, I see that some macro block layouts are overlapping, such as grid_clb and sb_1__1_:

![image](https://github.com/lnis-uofu/SOFA/assets/1922202/a2b3285a-8e71-4b27-9019-ea6ab5503489)

Do you have a script/command to avoid of placement of any cell for those overlapping regions? 

Regards,

Burak

**Comment by ganeshgore** [comment]
Hello Burak,

The lines you highlighted are just a bounding box of the cell (sb_1__1_). As we used a rectilinear (+) shape, the boundary of the cell and the bounding box of the cell are different. All the standard cells are placed within the boundary of the cell, so the overlapping bounding box is not a problem.

**Comment by mbaykenar** [comment]
I didn't notice that. As you mentioned I checked gds of sb_0__1_ and the shapes for switching blocks are not square.

![image](https://github.com/lnis-uofu/SOFA/assets/1922202/34898a5a-0680-428a-a004-c370cb5f2623)

I assume you chosed these rectiliniear shape to optimize floorplanning of tile-based architecture?

Regards,

**Comment by ganeshgore** [comment]
That's right, there are diagonal connections from CLB to SB modules. The rectilinear shape helps in that case.
