### ISSUE TITLE
Cannot run with newest version of OpenFPGA

### ISSUE THREAD

**Issue by franktaTian** [lnis-uofu/SOFA#147]
I use ther docker of  OpenFPGA( according the Document)
And clone the SOFA (this site)
docker run -it  -v ./SOFA:/home/openfpga_user/SOFA  ghcr.io/lnis-uofu/openfpga-master
Then , try to run SOFA , there is error :

openfpga_user@8ca4305f0016:\~/SOFA/FPGA1212_QLSOFA_HD_PNR$ make runOpenFPGA
OPENFPGA_PATH=/opt/openfpga
shopt
 INFO (     MainThread) - Set up to run 2 Parallel threads
 INFO (     MainThread) - Currently running task FPGA1212_QLSOFA_HD_task
 INFO (     MainThread) - Removing run_dir run001
 INFO (     MainThread) - Removing run_dir latest
 INFO (     MainThread) - Task execution completed
 INFO (     MainThread) - Set up to run 2 Parallel threads
 INFO (     MainThread) - Currently running task FPGA1212_QLSOFA_HD_task
 INFO (     MainThread) - Created "run001" directory for current task run
 INFO (     MainThread) - Running "yosys_vpr" flow
 INFO (     MainThread) - Found 1 Architectures 1 Benchmarks & 1 Script Parameters
 INFO (     MainThread) - Created total 1 jobs
ERROR (00_counter_MIN_ROUTE_CHAN_WIDTH) - Failed to execute openfpga flow - 00_counter_MIN_ROUTE_CHAN_WIDTH
Traceback (most recent call last):
  File "/opt/openfpga/openfpga_flow/scripts/run_fpga_task.py", line 572, in run_single_script
    raise subprocess.CalledProcessError(0, " ".join(command))
subprocess.CalledProcessError: Command 'python3.8 /opt/openfpga/openfpga_flow/scripts/run_fpga_flow.py /home/openfpga_user/SOFA/FPGA1212_QLSOFA_HD_PNR/FPGA1212_QLSOFA_HD_task/arch/vpr_arch.xml /home/openfpga_user/SOFA/FPGA1212_QLSOFA_HD_PNR/FPGA1212_QLSOFA_HD_task/BENCHMARK/counter/counter.v --top_module counter --run_dir /home/openfpga_user/SOFA/FPGA1212_QLSOFA_HD_PNR/FPGA1212_QLSOFA_HD_task/run001/vpr_arch/counter/MIN_ROUTE_CHAN_WIDTH --fpga_flow yosys_vpr --openfpga_shell_template /home/openfpga_user/SOFA/FPGA1212_QLSOFA_HD_PNR/FPGA1212_QLSOFA_HD_task/generate_testbench.openfpga --openfpga_arch_file /home/openfpga_user/SOFA/FPGA1212_QLSOFA_HD_PNR/FPGA1212_QLSOFA_HD_task/arch/openfpga_arch.xml --openfpga_sim_setting_file /opt/openfpga/openfpga_flow/openfpga_simulation_settings/auto_sim_openfpga.xml --external_fabric_key_file /home/openfpga_user/SOFA/FPGA1212_QLSOFA_HD_PNR/FPGA1212_QLSOFA_HD_task/arch/fabric_key.xml --openfpga_vpr_device_layout 12x12 --openfpga_vpr_route_chan_width 60 --power --power_tech /opt/openfpga/openfpga_flow/tech/PTM_45nm/45nm.xml --arch_variable_file /home/openfpga_user/SOFA/FPGA1212_QLSOFA_HD_PNR/FPGA1212_QLSOFA_HD_task/design_variables.yml --vpr_fpga_verilog --vpr_fpga_verilog_dir /home/openfpga_user/SOFA/FPGA1212_QLSOFA_HD_PNR/FPGA1212_QLSOFA_HD_task/run001/vpr_arch/counter/MIN_ROUTE_CHAN_WIDTH --vpr_fpga_x2p_rename_illegal_port --flow_config /home/openfpga_user/SOFA/FPGA1212_QLSOFA_HD_PNR/FPGA1212_QLSOFA_HD_task/config/task.conf --default_tool_path /opt/openfpga/openfpga_flow/scripts/../misc/fpgaflow_default_tool_path.conf --TOP counter' returned non-zero exit status 0.
X X X X X X Failed to generate netlist X X X X X X
**AND try to rerun the command:**
openfpga_user@8ca4305f0016:\~/SOFA/FPGA1212_QLSOFA_HD_PNR$ python3.8 /opt/openfpga/openfpga_flow/scripts/run_fpga_flow.py /home/openfpga_user/SOFA/FPGA1212_QLSOFA_HD_PNR/FPGA1212_QLSOFA_HD_task/arch/vpr_arch.xml /home/openfpga_user/SOFA/FPGA1212_QLSOFA_HD_PNR/FPGA1212_QLSOFA_HD_task/BENCHMARK/counter/counter.v --top_module counter --run_dir /home/openfpga_user/SOFA/FPGA1212_QLSOFA_HD_PNR/FPGA1212_QLSOFA_HD_task/run001/vpr_arch/counter/MIN_ROUTE_CHAN_WIDTH --fpga_flow yosys_vpr --openfpga_shell_template /home/openfpga_user/SOFA/FPGA1212_QLSOFA_HD_PNR/FPGA1212_QLSOFA_HD_task/generate_testbench.openfpga --openfpga_arch_file /home/openfpga_user/SOFA/FPGA1212_QLSOFA_HD_PNR/FPGA1212_QLSOFA_HD_task/arch/openfpga_arch.xml --openfpga_sim_setting_file /opt/openfpga/openfpga_flow/openfpga_simulation_settings/auto_sim_openfpga.xml --external_fabric_key_file /home/openfpga_user/SOFA/FPGA1212_QLSOFA_HD_PNR/FPGA1212_QLSOFA_HD_task/arch/fabric_key.xml --openfpga_vpr_device_layout 12x12 --openfpga_vpr_route_chan_width 60 --power --power_tech /opt/openfpga/openfpga_flow/tech/PTM_45nm/45nm.xml --arch_variable_file /home/openfpga_user/SOFA/FPGA1212_QLSOFA_HD_PNR/FPGA1212_QLSOFA_HD_task/design_variables.yml --vpr_fpga_verilog --vpr_fpga_verilog_dir /home/openfpga_user/SOFA/FPGA1212_QLSOFA_HD_PNR/FPGA1212_QLSOFA_HD_task/run001/vpr_arch/counter/MIN_ROUTE_CHAN_WIDTH --vpr_fpga_x2p_rename_illegal_port --flow_config /home/openfpga_user/SOFA/FPGA1212_QLSOFA_HD_PNR/FPGA1212_QLSOFA_HD_task/config/task.conf --default_tool_path /opt/openfpga/openfpga_flow/scripts/../misc/fpgaflow_default_tool_path.conf --TOP counter
INFO - Validating command line arguments
INFO - Run directory : /home/openfpga_user/SOFA/FPGA1212_QLSOFA_HD_PNR/FPGA1212_QLSOFA_HD_task/run001/vpr_arch/counter/MIN_ROUTE_CHAN_WIDTH
INFO - Running "yosys_vpr" Flow
INFO - Extracted lut_size size from arch XML = 4
INFO - Running Yosys with lut_size = 4
INFO - Launching Run yosys 
INFO - Run yosys is written in file yosys_output.log
INFO - ACE2 output is written in file counter_ace2_output.txt
INFO - blif_3args output is written in file counter_blif_3args_output.txt
INFO - Launching Yosys 
INFO - Yosys is written in file yosys_rewrite.log
INFO - Running OpenFPGA Shell Engine 
INFO - Launching OpenFPGA Shell Run 
INFO - OpenFPGAShell Revision: v8.0.0-9402-geb9722851 Compiled: 2024-04-14T00:12:57
**ERROR - OpenFPGA Shell Run run failed with returncode -6
ERROR - command /opt/openfpga/build/openfpga/openfpga -batch -f counter_run.openfpga
ERROR - -->>terminate called after throwing an instance of 'ArchFpgaError'
ERROR - -->>  what():  Unexpected tag <region> in section <fabric_key>, expected <module>
ERROR - Current working directory :** /home/openfpga_user/SOFA/FPGA1212_QLSOFA_HD_PNR/FPGA1212_QLSOFA_HD_task/run001/vpr_arch/counter/MIN_ROUTE_CHAN_WIDTH
ERROR - Failed to run OpenFPGA Shell Run task
ERROR - Exiting . . . . . .

**Comment by franktaTian** [comment]
Any help?

**Comment by LucaMartis00** [comment]
Hi @franktaTian did you solve the problem ?

**Comment by franktaTian** [comment]
> Hi @franktaTian did you solve the problem ?

Not yet. I think there maybe some mismatch of version. It is hard for me to debug it.

**Comment by LucaMartis00** [comment]
Hi @franktaTian If it can be helpful, I solved it by replacing in generate_generate_testbench.openfpga file: '--load_fabric_key ${EXTERNAL_FABRIC_KEY_FILE}' with 'generate_random_key'.

![image](https://github.com/lnis-uofu/SOFA/assets/142605978/697773a3-6b5e-46cd-951d-667df6f44802)

**Comment by franktaTian** [comment]
> Hi @franktaTian If it can be helpful, I solved it by replacing in generate_generate_testbench.openfpga file: '--load_fabric_key ${EXTERNAL_FABRIC_KEY_FILE}' with 'generate_random_key'.
> 
> ![image](https://private-user-images.githubusercontent.com/142605978/327954209-697773a3-6b5e-46cd-951d-667df6f44802.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NTYzOTMsIm5iZiI6MTcxNDk1NjA5MywicGF0aCI6Ii8xNDI2MDU5NzgvMzI3OTU0MjA5LTY5Nzc3M2EzLTZiNWUtNDZjZC05NTFkLTY2N2RmNmY0NDgwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQwMDQxMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjZiM2YzOWE1ZTIyYjhjMjU3N2IwZTdlMDBkYzI0ZmM4N2YxMmY1MGZkZjhlMzk4N2JmN2ZmNzZlZjM5NWQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MBbVTkDekfR6lKjthq1jqUhhRL4eWjuQEtz8FriqoMA)

Thank you for your help. I will try it.

**Comment by franktaTian** [comment]
Yes,It can work now!
